# Generated by Django 6.0.2 on 2026-02-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_ad_account', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_adset', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_status', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_ad', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_status', models.CharField(blank=True, max_length=100)),
                ('id_meta_adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='Dashboard.adset')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_campaign', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('created_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('effective_status', models.CharField(blank=True, max_length=100)),
                ('id_meta_ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='Dashboard.adaccount')),
            ],
        ),
        migrations.AddField(
            model_name='adset',
            name='id_meta_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='Dashboard.campaign'),
        ),
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_user', models.CharField(db_index=True, max_length=64, unique=True)),
                ('long_access_token', models.TextField()),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='adaccount',
            name='id_dashboard_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='Dashboard.dashboarduser'),
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_page', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('dashboard_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to='Dashboard.dashboarduser')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_instagram', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('accounts_reached', models.PositiveBigIntegerField(blank=True, null=True)),
                ('impressions', models.PositiveBigIntegerField(blank=True, null=True)),
                ('profile_views', models.PositiveBigIntegerField(blank=True, null=True)),
                ('accounts_engaged', models.PositiveBigIntegerField(blank=True, null=True)),
                ('follower_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('follows_and_unfollows', models.IntegerField(blank=True, null=True)),
                ('id_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='Dashboard.facebookpage')),
            ],
        ),
        migrations.CreateModel(
            name='MediaInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_meta_media', models.CharField(db_index=True, max_length=64, unique=True)),
                ('caption', models.TextField(blank=True)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reach', models.PositiveBigIntegerField(blank=True, null=True)),
                ('views', models.PositiveBigIntegerField(blank=True, null=True)),
                ('likes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('comments', models.PositiveBigIntegerField(blank=True, null=True)),
                ('saved', models.PositiveBigIntegerField(blank=True, null=True)),
                ('shares', models.PositiveBigIntegerField(blank=True, null=True)),
                ('plays', models.PositiveBigIntegerField(blank=True, null=True)),
                ('watch_time', models.PositiveBigIntegerField(blank=True, null=True)),
                ('avg_watch_time', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('id_meta_instagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='Dashboard.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'started_at'], name='Dashboard_s_status_0af529_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade', models.CharField(db_index=True, max_length=100)),
                ('mensagem', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Dashboard.syncrun')),
            ],
        ),
        migrations.CreateModel(
            name='AdInsightDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_diario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('impressao_diaria', models.PositiveBigIntegerField(default=0)),
                ('alcance_diario', models.PositiveBigIntegerField(default=0)),
                ('ctr_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpm_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpc_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('frequencia_media', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quantidade_clicks_diaria', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateField(db_index=True)),
                ('id_meta_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insights', to='Dashboard.ad')),
            ],
            options={
                'indexes': [models.Index(fields=['id_meta_ad', 'created_at'], name='Dashboard_a_id_meta_571991_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_meta_ad', 'created_at'), name='uniq_ad_insight_daily')],
            },
        ),
        migrations.CreateModel(
            name='AdSetInsightDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_diario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('impressao_diaria', models.PositiveBigIntegerField(default=0)),
                ('alcance_diario', models.PositiveBigIntegerField(default=0)),
                ('ctr_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpm_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpc_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('frequencia_media', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quantidade_clicks_diaria', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateField(db_index=True)),
                ('id_meta_adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insights', to='Dashboard.adset')),
            ],
            options={
                'indexes': [models.Index(fields=['id_meta_adset', 'created_at'], name='Dashboard_a_id_meta_0d8c05_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_meta_adset', 'created_at'), name='uniq_adset_insight_daily')],
            },
        ),
        migrations.CreateModel(
            name='CampaignInsightDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_diario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('impressao_diaria', models.PositiveBigIntegerField(default=0)),
                ('alcance_diario', models.PositiveBigIntegerField(default=0)),
                ('ctr_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpm_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpc_medio', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('frequencia_media', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('quantidade_clicks_diaria', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateField(db_index=True)),
                ('id_meta_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insights', to='Dashboard.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['id_meta_campaign', 'created_at'], name='Dashboard_c_id_meta_3b4e75_idx')],
                'constraints': [models.UniqueConstraint(fields=('id_meta_campaign', 'created_at'), name='uniq_campaign_insight_daily')],
            },
        ),
        migrations.AddIndex(
            model_name='dashboarduser',
            index=models.Index(fields=['expired_at'], name='Dashboard_d_expired_567fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='mediainstagram',
            index=models.Index(fields=['id_meta_instagram', 'timestamp'], name='Dashboard_m_id_meta_d526fc_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['sync_run', 'timestamp'], name='Dashboard_s_sync_ru_5a2625_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['entidade', 'timestamp'], name='Dashboard_s_entidad_38601f_idx'),
        ),
    ]
