# Generated by Django 6.0.2 on 2026-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediainstagram',
            name='media_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
