# Generated by Django 6.0.2 on 2026-02-26 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_adinsightdaily_quantidade_results_diaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id_meta_ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacoes', to='Dashboard.adaccount')),
            ],
            options={
                'ordering': ['-data_criacao'],
                'indexes': [models.Index(fields=['id_meta_ad_account', 'data_criacao'], name='Dashboard_a_id_meta_45ddd1_idx')],
            },
        ),
    ]
