# Generated by Django 6.0.2 on 2026-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
