# Generated by Django 6.0.2 on 2026-02-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_cliente_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='forma_pagamento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gasto_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nicho_atuacao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='periodo_cobranca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_investido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
