# Generated by Django 6.0.2 on 2026-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_cliente_forma_pagamento_cliente_gasto_diario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('CARTAO CREDITO', 'CARTAO CREDITO')], default='PIX', max_length=20),
        ),
    ]
