# Generated by Django 6.0.2 on 2026-02-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_cliente_forma_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='periodo_cobranca',
            field=models.CharField(choices=[('SEMANAL', 'SEMANAL'), ('MENSAL', 'MENSAL')], default='MENSAL', max_length=20),
        ),
    ]
