# Generated by Django 6.0.2 on 2026-06-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_alter_cliente_periodo_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descricao_estado',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('MAU', 'MAU'), ('REGULAR', 'REGULAR'), ('BOM', 'BOM')], db_index=True, default='REGULAR', max_length=20),
        ),
    ]
